# Generated by Django 4.1.1 on 2022-09-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10)),
                ('resident', models.CharField(max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('registration_date', models.DateField()),
                ('date_of_birth', models.DateField(null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorce', 'Divorce'), ('Widow', 'Widow')], default='', max_length=10)),
                ('name_of_spouse', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone_number_of_spouse', models.IntegerField()),
                ('baptism', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('church_of_baptism', models.CharField(blank=True, max_length=70, null=True)),
                ('emergency_contact_person', models.CharField(max_length=50)),
                ('emergency_contact_number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
