# Generated by Django 4.1.1 on 2022-09-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number_of_spouse',
            field=models.IntegerField(null=True),
        ),
    ]
