# Generated by Django 4.1.1 on 2022-09-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_member_first_name_alter_member_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number_of_spouse',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
