# Generated by Django 4.1.1 on 2022-10-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_member_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number_of_spouse',
            field=models.CharField(blank=True, default=1, max_length=10, null=True),
        ),
    ]
